import type { Match, LeaderboardEntry } from './types'

// TODO: Replace with Supabase query — supabase.from('matches').select('*')
export const MOCK_MATCHES: Match[] = [
  {
    id: '1',
    team_home: 'Mexico',
    team_away: 'Canada',
    flag_home: '🇲🇽',
    flag_away: '🇨🇦',
    match_date: '2026-06-11',
    status: 'upcoming',
    group: 'A',
  },
  {
    id: '2',
    team_home: 'USA',
    team_away: 'Colombia',
    flag_home: '🇺🇸',
    flag_away: '🇨🇴',
    match_date: '2026-06-11',
    status: 'upcoming',
    group: 'A',
  },
  {
    id: '3',
    team_home: 'Argentina',
    team_away: 'Algeria',
    flag_home: '🇦🇷',
    flag_away: '🇩🇿',
    match_date: '2026-06-12',
    status: 'upcoming',
    group: 'B',
  },
  {
    id: '4',
    team_home: 'France',
    team_away: 'Senegal',
    flag_home: '🇫🇷',
    flag_away: '🇸🇳',
    match_date: '2026-06-12',
    status: 'upcoming',
    group: 'B',
  },
  {
    id: '5',
    team_home: 'Spain',
    team_away: 'Japan',
    flag_home: '🇪🇸',
    flag_away: '🇯🇵',
    match_date: '2026-06-13',
    status: 'upcoming',
    group: 'C',
  },
  {
    id: '6',
    team_home: 'England',
    team_away: 'Croatia',
    flag_home: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    flag_away: '🇭🇷',
    match_date: '2026-06-13',
    status: 'upcoming',
    group: 'C',
  },
  {
    id: '7',
    team_home: 'Brazil',
    team_away: 'Morocco',
    flag_home: '🇧🇷',
    flag_away: '🇲🇦',
    match_date: '2026-06-14',
    status: 'upcoming',
    group: 'D',
  },
  {
    id: '8',
    team_home: 'Germany',
    team_away: 'South Korea',
    flag_home: '🇩🇪',
    flag_away: '🇰🇷',
    match_date: '2026-06-14',
    status: 'upcoming',
    group: 'D',
  },
  {
    id: '9',
    team_home: 'Portugal',
    team_away: 'Australia',
    flag_home: '🇵🇹',
    flag_away: '🇦🇺',
    match_date: '2026-06-15',
    status: 'upcoming',
    group: 'E',
  },
  {
    id: '10',
    team_home: 'Netherlands',
    team_away: 'Ecuador',
    flag_home: '🇳🇱',
    flag_away: '🇪🇨',
    match_date: '2026-06-15',
    status: 'upcoming',
    group: 'E',
  },
  {
    id: '11',
    team_home: 'Italy',
    team_away: 'Nigeria',
    flag_home: '🇮🇹',
    flag_away: '🇳🇬',
    match_date: '2026-06-16',
    status: 'upcoming',
    group: 'F',
  },
  {
    id: '12',
    team_home: 'Belgium',
    team_away: 'Uruguay',
    flag_home: '🇧🇪',
    flag_away: '🇺🇾',
    match_date: '2026-06-16',
    status: 'upcoming',
    group: 'F',
  },
]

// TODO: Replace with Supabase query — supabase.from('leaderboard').select('*').order('total_score', { ascending: false })
export const MOCK_LEADERBOARD: LeaderboardEntry[] = [
  { rank: 1, user_id: 'u1', display_name: 'Ahmed', total_score: 42, correct_predictions: 14, total_predictions: 18 },
  { rank: 2, user_id: 'u2', display_name: 'Ali', total_score: 39, correct_predictions: 13, total_predictions: 18 },
  { rank: 3, user_id: 'u3', display_name: 'Hassan', total_score: 36, correct_predictions: 12, total_predictions: 18 },
  { rank: 4, user_id: 'u4', display_name: 'Omar', total_score: 33, correct_predictions: 11, total_predictions: 18 },
  { rank: 5, user_id: 'u5', display_name: 'Zain', total_score: 30, correct_predictions: 10, total_predictions: 18 },
  { rank: 6, user_id: 'u6', display_name: 'Sara', total_score: 27, correct_predictions: 9, total_predictions: 18 },
  { rank: 7, user_id: 'u7', display_name: 'Fatima', total_score: 24, correct_predictions: 8, total_predictions: 18 },
  { rank: 8, user_id: 'u8', display_name: 'Yusuf', total_score: 21, correct_predictions: 7, total_predictions: 18 },
  { rank: 9, user_id: 'u9', display_name: 'Bilal', total_score: 18, correct_predictions: 6, total_predictions: 18 },
  { rank: 10, user_id: 'u10', display_name: 'Aisha', total_score: 15, correct_predictions: 5, total_predictions: 18 },
]
